### ISSUE TITLE
"Incoming request URL" field always reset to "facebook" when leave blank

### ISSUE THREAD

**Issue by RemiC2care** [Adsmurai-Google-Tag-Manager-Templates/adsmurai-facebook-conversions-api-client#3]
When I delete "facebook" from "Incoming request URL" field and then press save, it reset to "facebook" when i reopen the client.

On the tooltip it's noted : 

Choose which page path you want to use for listening to requests containing Facebook events data. The path on the incoming request must exactly match this field.

E.g.: If you enter "facebook", this client will listen for requests to https://your-server-side-gtm-container.com/facebook, but won't listen for requests to https://your-server-side-gtm-container.com/facebook-tracking.

**Leave empty to target the base URL.**

**Comment by angelbt91** [comment]
Hi @RemiC2care!

Thanks for opening this issue!

Exactly, it seems that if there's set a default value on a text field (like "facebook" in this case), then that field will default to such value even when you explicitly and manually delete it.

As GTM server will be used for other tracking purposes other than Facebook, I think it's important to keep a default value, to avoid users using the base URL unintentionally. However, that "Leave empty to target the base URL" sentence is really misleading, as there's no way to leave it empty. I will remove it on the next version of the client and notify that such change is live in this issue.

Thank you very much for pointing this out! If there's something else I can help you with, just let me know.

Thanks!
