### ISSUE TITLE
Incoming Request URL - Client Configuration Bug

### ISSUE THREAD

**Issue by kuber-kalra** [Adsmurai-Google-Tag-Manager-Templates/adsmurai-facebook-conversions-api-client#4]
"Incoming request URL" field while configuring a client is autofilled with the value "facebook". Removing the facebook value and leaving it empty does nothing and the value gets repopulated with the value "facebook". This is causing some tracking issues as we want to target base URL which we aren't able to.

<img width="1109" alt="Screenshot 2023-09-22 at 18 42 47" src="https://github.com/Adsmurai-Google-Tag-Manager-Templates/adsmurai-facebook-conversions-api-client/assets/94118154/09fc1864-18c9-4faa-9582-8efc87054f98">

**Comment by mjadsmurai** [comment]
Please see: https://github.com/Adsmurai-Google-Tag-Manager-Templates/adsmurai-facebook-conversions-api-client/issues/3
I'm closing this issue as duplicated.
