### ISSUE TITLE
Getting Http 400 Error 

### ISSUE THREAD

**Issue by surya-ravi** [Adsmurai-Google-Tag-Manager-Templates/adsmurai-facebook-conversions-api-client#9]
Hello there, we've set up CAPI tracking using your latest tag and client templates on Google tag manager with Cloud Run and it has been working fine for a long time. Just recently we are receiving HTTP 400 errors for all requests and not sure where exactly to debug this.

But I've noticed that when I enter the FB Event Test Code in the client, its working fine. Once we remove it, get 400 errors.

I'm not sure if this is the right place for this query but any support would be much appreciated!

This is where we've hosted the container: https://server-side-tagging-514362109381.us-central1.run.app (custom domain: firebase.purnamcommunity.in )

Thank you.

<img width="762" alt="SCR-20240913-shys" src="https://github.com/user-attachments/assets/8a0530bb-ae28-4069-98f8-256617e8dea7">

**Comment by mjadsmurai** [comment]
Hi! I'm afraid we do not offer tech support on selfhosted as it's deprecated.
Regards!

**Comment by YahyaAhmad** [comment]
click "preview" and see the logs, my problem was that the request URL was not matching.

**Comment by surya-ravi** [comment]
> click "preview" and see the logs, my problem was that the request URL was not matching.

This seems to have fixed it. I removed the default facebook request URL. Thank you @YahyaAhmad
